services:

  oracle-fhir:
    container_name: oracle-fhir
    restart: always
    image: oracle-local
    volumes:
      - oracle-data:/opt/oracle/oradata
    env_file:
      - fhir.env
    ports:
      - "1521:1521"
      - "5500:5500"

  hapi-fhir-ora:
    depends_on:
      - oracle-fhir
    image: hapiproject/hapi:v6.8.3
    container_name: hapi-fhir-ora
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//localhost:1521/FHIR1
      - _JAVA_OPTIONS=-Xmx4g -Xms4g
    env_file:
      - fhir.env
    ports:
      - "8088:8080"
    configs:
      - source: hapi-ora
        target: /app/config/application.yaml

volumes:
  oracle-data:
    external: true

configs:
  hapi-ora:
    file: ./application-ora.yaml
