version: "3.7"
services:

  postgres-fhir:
    container_name: postgres-fhir
    restart: always
    image: postgres:15.4
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - fhir.env
    ports:
      - "5432:5432"

  hapi-fhir:
    depends_on:
      - postgres-fhir
    image: hapiproject/hapi:v6.8.3
    container_name: hapi-fhir-main
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-fhir:5432/fhir
      - _JAVA_OPTIONS=-Xmx4g -Xms4g
    env_file:
      - fhir.env
    ports:
      - "8088:8080"
    configs:
      - source: hapi-postgres
        target: /app/config/application.yaml

volumes:
    postgres:
      external: true

configs:
  hapi-postgres:
    file: ./application-postgresql.yaml
